from PIL import Image, ImageFont, ImageDraw
import sys

# JetBrains Mono — SIL Open Font License 1.1 (see third_party/font/OFL.txt).
# Freely redistributable, so the rasterized glyphs may ship in the binary.
FONT_CANDIDATES = [
    ("third_party/font/JetBrainsMono-Regular.ttf", 0),
]
def load(size):
    for path, idx in FONT_CANDIDATES:
        try:
            return ImageFont.truetype(path, size, index=idx)
        except Exception:
            continue
    raise SystemExit("no monospace font found")

FIRST, LAST = 32, 126
def gen(name, size):
    font = load(size)
    asc, desc = font.getmetrics()
    cellH = asc + desc
    # monospace advance width
    w = font.getbbox("M")[2]
    try:
        adv = font.getlength("M")
        cellW = int(round(adv))
    except Exception:
        cellW = w
    if cellW < 1: cellW = w
    glyphs = []
    for c in range(FIRST, LAST + 1):
        img = Image.new("L", (cellW, cellH), 0)
        d = ImageDraw.Draw(img)
        d.text((0, 0), chr(c), fill=255, font=font)
        glyphs.append(img.tobytes())
    return cellW, cellH, glyphs

def emit(out):
    body = gen("body", 16)    # ~10px wide, matches the old Menlo body cell
    title = gen("title", 23)  # ~14-15px wide title
    with open(out, "w") as f:
        f.write("/* font.h - generated by tools/genfont.py. ASCII 32..126, 8-bit alpha. */\n")
        f.write("#ifndef FONT_H\n#define FONT_H\n")
        f.write("typedef struct { int w, h, first, count; const unsigned char *data; } Font;\n")
        for nm, (w, h, glyphs) in (("body", body), ("title", title)):
            data = b"".join(glyphs)
            f.write(f"static const unsigned char {nm}_data[] = {{\n")
            for i in range(0, len(data), 20):
                f.write(",".join(str(b) for b in data[i:i+20]) + ",\n")
            f.write("};\n")
            f.write(f"static const Font font_{nm} = {{ {w}, {h}, {FIRST}, {LAST-FIRST+1}, {nm}_data }};\n")
        f.write("#endif\n")
    print(f"wrote {out}: body {body[0]}x{body[1]}, title {title[0]}x{title[1]}")

emit("src/font.h")
